### ISSUE TITLE
How to train yolov5 with those shapes accorgind to commit changes?

### ISSUE THREAD

**Issue by ablyzniuk** [trinhtuanvubk/yolo-ncnn-cpp#1]
Hi,
How can I properly train the yolov5 model with a custom head due to changes in the output shapes? I saw that only forward function was changed, but I think It will impact the training run. 
 
Best regards, looking forward to your reply ASAP.
P.S. Would you happen to have any code examples of how to decode yolov5 output shape from the latest Ultralytics commits? (Output shape is (1, 84, 8400, 
 I did it via example from the official repo, because it is similar yolov8 outзге shape, but the result is unsatisfying)
I'm trying to reproduce steps that you described and it is unsuccessful...

**Comment by trinhtuanvubk** [comment]
The changed forward code is only used for inference, and you can use the official checkpoint from Ultralytics.
I also see that Ultralytics now supports converting to NCCN. I found this way in an Ultralytics issue, so I think their official code is better.

**Comment by trinhtuanvubk** [comment]
I think the reason why we changed the forward code at that time because there were post-processing code inside forward func (it may raise some errors). It should have been separated. We just want to convert the real weight of model to onnx, nccn. Poss-process code should be implemented in c++.

**Comment by ablyzniuk** [comment]
So, in any case I should to reproduce ultralytics post-process code on c++ for ncnn(their yolov5 ncnn implementation)?

**Comment by trinhtuanvubk** [comment]
not in every case:
- You still can add post-process with a wrapper model class when converting model to onnx, ncnn. This way is not always successful because converting progress should be straight forward (post-process sometimes contains if-else, for-loop that raises error). 
- In cases cant be straight forward, we should convert real model only (this repo is like that, post process is implemented in c++).
-> I didnt read the newest code of Ultralytics so I dont know what they changed (re-implement postprocess to avoid straight forward error or convert model only and postprocess).
Hope it help you a bit

**Comment by ablyzniuk** [comment]
@trinhtuanvubk I'm thankful for your reply!!! It will :) Thank you)
Best regards and have a great day)
